<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd Pilih Tabungan</name>
   <tag></tag>
   <elementGuidId>8c150ca5-55d9-444f-a20f-3926897b57fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='solutionFinder']/section[3]/div[3]/div/div[2]/div/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.jcf-select.jcf-unselectable.jcf-select-formControl.jcf-drop-active.jcf-focus > span.jcf-select-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>32861062-3352-423b-8c1d-6e902a255a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jcf-select-text</value>
      <webElementGuid>c25c2a58-1412-4f34-a9c8-530d313afa3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Silakan pilih -</value>
      <webElementGuid>0b7f4524-bfb3-4f69-9fd5-a1057c009c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;solutionFinder&quot;)/section[@class=&quot;body-step body-step--3 current&quot;]/div[@class=&quot;content-finder form form--finder&quot;]/div[@class=&quot;content-finder__box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;form-group&quot;]/span[@class=&quot;jcf-select jcf-unselectable jcf-select-formControl jcf-drop-active jcf-focus&quot;]/span[@class=&quot;jcf-select-text&quot;]</value>
      <webElementGuid>d0309165-ffc5-4131-bd0c-c6e2c0d57bce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='solutionFinder']/section[3]/div[3]/div/div[2]/div/div/span/span</value>
      <webElementGuid>cf1790bf-d6e1-41e0-a3c8-c06dd5d715a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tabungan rutin Anda per bulan'])[1]/following::span[2]</value>
      <webElementGuid>f4d581a5-0bd1-4ac5-b7d4-188e793386e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rata-rata pengeluaran Anda/ Keluarga per bulan'])[1]/following::span[6]</value>
      <webElementGuid>9614cb98-a2ae-47ec-9370-01b894334756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Silakan pilih -'])[8]/preceding::span[5]</value>
      <webElementGuid>7c12051f-9833-48f0-ac1a-d82b546f7fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/span</value>
      <webElementGuid>a7ca4128-7be7-4bac-896c-6d286e9582ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '- Silakan pilih -' or . = '- Silakan pilih -')]</value>
      <webElementGuid>947f4f0b-308f-4437-ae82-1e99d3cb2ca4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
