<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pilih Belum Menikah</name>
   <tag></tag>
   <elementGuidId>4e110be3-11fa-4535-a78c-fbac39e1b89d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='single']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#single</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7e5efbb-21d9-46ae-9bb3-81c668afbf8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9da2b60a-5a1e-4ca6-99ae-a2a14e8e71a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>single</value>
      <webElementGuid>e6259a1d-f43e-4fa0-9ea3-9a4ef28dbe09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control--radio formControl</value>
      <webElementGuid>970b9439-3aae-46af-8fe6-99f4b90f9da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>married</value>
      <webElementGuid>40172e4b-1426-4531-973a-df28d02aca81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>single</value>
      <webElementGuid>78c477a2-2ce9-4ec2-a2a6-57d23929911b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single&quot;)</value>
      <webElementGuid>88a66c74-69ac-4000-a856-6106bf043d96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='single']</value>
      <webElementGuid>c2573960-9829-445f-83c6-ea43bbe9e3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='solutionFinder']/section[2]/div[3]/div/div[2]/div/div/div/div/label/span/input</value>
      <webElementGuid>f5c4d2dd-9615-45de-971e-9d69e40fbd90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/label/span/input</value>
      <webElementGuid>8fcca9bc-eb8f-4ca7-a9af-ac6e92fe07fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'single' and @name = 'married']</value>
      <webElementGuid>e3470a01-6c5e-4e20-8908-76498dfeb112</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
