<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select Jenis Kelamin</name>
   <tag></tag>
   <elementGuidId>73b5f4b1-c5cb-4dc5-ac4a-86bb4bdb977d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='jenis_kelamin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;jenis_kelamin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b83e80e3-15ec-417a-97ba-e0f427d53326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>80d4a09b-6b27-4a94-89cf-c7f19b2b8325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control--radio formControl</value>
      <webElementGuid>1c4f4a72-21b1-4edf-90a3-ceeee3a5c350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jenis_kelamin</value>
      <webElementGuid>fe2381be-f118-4332-89c9-d24917573aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>male</value>
      <webElementGuid>1f035e36-bde7-45ff-9f94-cc2a512d9aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;solutionFinder&quot;)/section[@class=&quot;body-step body-step--2 current&quot;]/div[@class=&quot;content-finder form form--finder&quot;]/div[@class=&quot;content-finder__box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 col-xs-4&quot;]/div[@class=&quot;form-group form-group--icon&quot;]/label[@class=&quot;label label--male margin-right-10&quot;]/span[@class=&quot;jcf-radio jcf-unchecked jcf-focus&quot;]/input[@class=&quot;form-control form-control--radio formControl&quot;]</value>
      <webElementGuid>2fa66579-0cb5-4265-ba12-60995a181b32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='jenis_kelamin']</value>
      <webElementGuid>95390fa9-6d12-49e2-8d05-87b771bd8ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='solutionFinder']/section[2]/div[3]/div/div/div/div/label[2]/span/input</value>
      <webElementGuid>97c8d7e8-9f1b-4956-9ee6-281f1084b0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>ba5eabbb-0fb2-4318-beee-b838e0fbd4c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'jenis_kelamin']</value>
      <webElementGuid>94e51d79-672b-4929-9b36-d5a10659b1fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
